### ISSUE TITLE
run 'remodel-gen' command error

### ISSUE THREAD

**Issue by JourneyWind** [facebook/remodel#19]
try to generates the sample value file encounter a error:

 remodel-gen ~/desktop/AddressBookContact.value

/usr/local/lib/node_modules/remodel-gen/bin/dist/js/object-mona-parser/value-object/value-object-parser.js:32
    foundType: parsedType
               ^

ReferenceError: parsedType is not defined
    at Object.parse [as parseValueObject] (/usr/local/lib/node_modules/remodel-gen/bin/dist/js/object-mona-parser/value-object/value-object-parser.js:32:16)
    at Object.parse (/usr/local/lib/node_modules/remodel-gen/bin/dist/value-object-parser.js:72:35)
    at evaluateUnparsedValueObjectCreationRequest (/usr/local/lib/node_modules/remodel-gen/bin/dist/value-objects.js:31:41)
    at right (/usr/local/lib/node_modules/remodel-gen/bin/dist/either.js:46:39)
    at match (/usr/local/lib/node_modules/remodel-gen/bin/dist/either.js:34:16)
    at Object.mbind (/usr/local/lib/node_modules/remodel-gen/bin/dist/either.js:47:12)
    at parseValues (/usr/local/lib/node_modules/remodel-gen/bin/dist/value-objects.js:39:47)
    at /usr/local/lib/node_modules/remodel-gen/bin/dist/logged-sequence-utils.js:20:26
    at /usr/local/lib/node_modules/remodel-gen/bin/dist/promise.js:74:12
    at /usr/local/lib/node_modules/remodel-gen/bin/dist/promise.js:30:13

**Comment by JourneyWind** [comment]
value-object-parser.js 中的函数存在兼容性问题. 问题是ES6以后 const 的作用域发生了变化
function parse(fileInput) {
  try {
    const parsedType = mona.parse(parseCommon.parseNamedAttributeGroupWithIncludes(), fileInput);

  } catch (e) {
    return {
      errorReason:e.message,
      isValid:false,
      foundType: null
    };
  }
  return {
    errorReason: null,
    isValid: true,
    foundType: parsedType
  };
}

 http://stackoverflow.com/questions/33457167/javascript-define-a-constant-inside-try-catch-with-strict-mode
