### ISSUE TITLE
ReferenceError: parsedType is not defined

### ISSUE THREAD

**Issue by LazyChild** [facebook/remodel#20]
When I run `remodel-gen`,
```

/usr/local/lib/node_modules/remodel-gen/bin/dist/js/object-mona-parser/value-object/value-object-parser.js:32
    foundType: parsedType
               ^

ReferenceError: parsedType is not defined
    at Object.parse [as parseValueObject] (/usr/local/lib/node_modules/remodel-gen/bin/dist/js/object-mona-parser/value-object/value-object-parser.js:32:16)
    at Object.parse (/usr/local/lib/node_modules/remodel-gen/bin/dist/value-object-parser.js:72:35)
    at evaluateUnparsedValueObjectCreationRequest (/usr/local/lib/node_modules/remodel-gen/bin/dist/value-objects.js:31:41)
    at right (/usr/local/lib/node_modules/remodel-gen/bin/dist/either.js:46:39)
    at match (/usr/local/lib/node_modules/remodel-gen/bin/dist/either.js:34:16)
    at Object.mbind (/usr/local/lib/node_modules/remodel-gen/bin/dist/either.js:47:12)
    at parseValues (/usr/local/lib/node_modules/remodel-gen/bin/dist/value-objects.js:39:47)
    at /usr/local/lib/node_modules/remodel-gen/bin/dist/logged-sequence-utils.js:20:26
    at /usr/local/lib/node_modules/remodel-gen/bin/dist/promise.js:74:12
    at /usr/local/lib/node_modules/remodel-gen/bin/dist/promise.js:30:13
```

**Comment by andrewcuneo** [comment]
Sorry, this was an issue that only affected people running node 6.0. It was fixed by https://github.com/facebook/remodel/commit/004d51040acfe824e2adcc545e02599ae3763ca0, and should be in the version bump that went out today.
