### ISSUE TITLE
Issue Getting IGListDiffable Plugin Installed

### ISSUE THREAD

**Issue by DreamingInBinary** [facebook/remodel#92]
I've not used Typescript much before (in fact, just installed it before using Remodel) and use NPM maybe twice a year, so I might be missing something entirely obvious. I've browsed the past issues and wasn't able to get things quite working.

I'm attempting to install the IGListDiffable plugin documented [here](https://github.com/Instagram/IGListKit/blob/master/Guides/Generating%20your%20models.md). The hang up occurs when I try to build things.

I've cloned this repo locally, and for brevity it's installed at something like this:
`desktop/test/remodel-master`

With a clean clone, I'm not quite able to build it:
`cd /path/to/remodel`
`./bin/build`

I get this error (it seems it can't locate `promise.ts` which appears to be in the `src `folder):

```
/Users/Jordan/Desktop/Test/remodel-master/bin/build ; exit;
module.js:549
    throw err;
    ^

Error: Cannot find module 'promise'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Jordan/Desktop/Test/remodel-master/bin/build.js:10:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

More than happy to provide more details, and thanks releasing such a useful project!

**Comment by DreamingInBinary** [comment]
As suspected, this was due to my ignorance with NPM. If any other devs run into issues running the build script, it's likely that you just simply need to run `npm install` in the same directory of wherever Remodel's `package.json` file is at. It seems this is analogous to Cocoapod's `Podfile`, as it installs all of the dependencies needed.
